export const MenuListKebab = [
    {
        idList: "22",
        name: "Kebabpizza",
        description: "Kebabkött, Lök, Champinjoner, Kebabsås",
        price: 125,
        kat: "kebab",
    },
    {
        idList: "23",
        name: "Mikael",
        description: "Kebabkött, Räkor, Jalapeno, Cayennepeppar, Kebabsås",
        price: 135,
        kat: "kebab",
    },
    {
        idList: "24",
        name: "Andreas",
        description: "Kebabkött, Skinka, Ananas, Salami, Bacon, Kebabsås",
        price: 135,
        kat: "kebab",
    },
    {
        idList: "25",
        name: "Tobias",
        description: "Kebabkött, Lök, Isbergssallad, Färska Tomater, Gurka, Kebabsås",
        price: 135,
        kat: "kebab",
    },
    {
        idList: "26",
        name: "Marieholm",
        description: "Kebabkött, Fläskfilé, Bacon, Champinjoner, Räkor, Lök, Cayennepeppar, Kebabsås",
        price: 135,
        kat: "kebab",
    },
    {
        idList: "27",
        name: "Martin",
        description: "Kebabkött, Skinka, Räkor, Oxfilé, Champinjoner, Kebabsås",
        price: 135,
        kat: "kebab",
    },
    {
        idList: "28",
        name: "Sol",
        description: "Kebabkött, Skinka, Champinjoner, Räkor, Ananas, Sparris, Kebabsås",
        price: 135,
        kat: "kebab",
    },
    {
        idList: "29",
        name: "Per",
        description: "Kebabkött, Skinka, Strips, Kebabsås",
        price: 135,
        kat: "kebab",
    },
    {
        idList: "30",
        name: "George",
        description: "Kebabkött, Lök, Champinjoner, Strips, Kebabsås",
        price: 135,
        kat: "kebab",
    },
    {
        idList: "31",
        name: "Taxi",
        description: "Kebabkött, Skinka, Lök, Strips, Isbergssallad, Tomat, Gurka, Kebabsås",
        price: 140,
        kat: "kebab",
    },
    
]