export const MenuListKyckling = [
    {
        idList: "35",
        name: "Kycklingkebabpizza 1",
        description: "Kycklingkebab, Lök, Champinjoner, Kebabsås",
        price: 125,
        kat: "kkebab",
    },
    {
        idList: "36",
        name: "Kycklingkebabpizza 2",
        description: "Kycklingkebab, Banan, Jordnötter, Curry, Kebabsås",
        price: 135,
        kat: "kkebab",
    },
    {
        idList: "37",
        name: "Kycklingkebabpizza 3",
        description: "Kycklingkebab, Räkor, Ananas, Kebabsås",
        price: 135,
        kat: "kkebab",
    },
    {
        idList: "38",
        name: "Kycklingkebabpizza 4",
        description: "Kycklingkebab, Champinjoner, Strips, Vitlökssås",
        price: 135,
        kat: "kkebab",
    },
    {
        idList: "39",
        name: "Kycklingkebabpizza 5",
        description: "Kycklingkebab, Isbergssallad, Gurka, Tomat, Kebabsås",
        price: 135,
        kat: "kkebab",
    },
    {
        idList: "40",
        name: "Kycklingpizza",
        description: "Kycklingfilé, Champinjoner, Paprika, Färsk vitlök",
        price: 120,
        kat: "kfile",
    },
    {
        idList: "41",
        name: "Terminator",
        description: "Kycklingfilé, Skinka, Bacon, Jalapeno, Curry, Jordnötter",
        price: 130,
        kat: "kfile",
    },
    {
        idList: "42",
        name: "Johanna",
        description: "Kycklingfilé, Banan, Ananas, Curry, Strips, Aioli/Kebabsås",
        price: 135,
        kat: "kfile",
    },
    {
        idList: "43",
        name: "Marianne",
        description: "Kycklingfilé, Bacon, Räkor, Aioli",
        price: 130,
        kat: "kfile",
    },
    {
        idList: "44",
        name: "Juventus",
        description: "Kycklingfilé, Färsk Paprika, Bacon, Färsk Vitlök, Kebabsås",
        price: 130,
        kat: "kfile",
    },
    
]